#!/bin/bash
# NuCRM Enterprise Page Test Script
# Tests each page by navigating via curl and checking HTTP status

RESULTS_FILE="/home/vinayak_shruti_biz/nucrm-enterprise/PAGE_TEST_RESULTS.txt"
BASE_URL="http://localhost:3000"

echo "========================================" > "$RESULTS_FILE"
echo "NUCRM ENTERPRISE - PAGE TEST RESULTS" >> "$RESULTS_FILE"
echo "Date: $(date)" >> "$RESULTS_FILE"
echo "========================================" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

PASS=0
FAIL=0

test_page() {
    local url="$1"
    local name="$2"
    local status=$(curl -s -o /dev/null -w "%{http_code}" -b "next-auth.session-token=test" "$BASE_URL$url" 2>/dev/null)
    
    if [ "$status" = "200" ] || [ "$status" = "302" ] || [ "$status" = "307" ]; then
        echo "P | $status | $url | $name" >> "$RESULTS_FILE"
        PASS=$((PASS + 1))
    else
        echo "F | $status | $url | $name" >> "$RESULTS_FILE"
        FAIL=$((FAIL + 1))
    fi
}

echo "Testing Public Pages..."
test_page "/" "Landing Page"
test_page "/offline" "Offline Page"
test_page "/health" "Health Check"
test_page "/setup" "Setup Page"
test_page "/docs" "Docs Page"
test_page "/api-docs" "API Docs"
test_page "/lead-capture" "Lead Capture"
test_page "/test-js" "Test JS Page"

echo "Testing Auth Pages..."
test_page "/auth/login" "Login"
test_page "/auth/login-simple" "Login Simple"
test_page "/auth/signup" "Signup"
test_page "/auth/forgot-password" "Forgot Password"
test_page "/auth/reset-password" "Reset Password"
test_page "/auth/verify-email" "Verify Email"
test_page "/auth/invite" "Invite"
test_page "/auth/no-workspace" "No Workspace"

echo "Testing Portal Pages..."
test_page "/portal" "Portal Home"
test_page "/portal/invoices" "Portal Invoices"
test_page "/portal/kb" "Portal Knowledge Base"
test_page "/portal/tickets" "Portal Tickets"

echo "Testing Super Admin Pages..."
test_page "/superadmin/dashboard" "Super Admin Dashboard"
test_page "/superadmin/tenants" "Tenants List"
test_page "/superadmin/users" "Users"
test_page "/superadmin/billing" "Billing"
test_page "/superadmin/analytics" "Analytics"
test_page "/superadmin/revenue" "Revenue"
test_page "/superadmin/usage" "Usage"
test_page "/superadmin/errors" "Errors"
test_page "/superadmin/health" "Health"
test_page "/superadmin/monitoring" "Monitoring"
test_page "/superadmin/backups" "Backups"
test_page "/superadmin/selective-restore" "Selective Restore"
test_page "/superadmin/modules" "Modules"
test_page "/superadmin/templates" "Templates"
test_page "/superadmin/announcements" "Announcements"
test_page "/superadmin/tickets" "Support Tickets"
test_page "/superadmin/docs" "Documentation"
test_page "/superadmin/data-explorer" "Data Explorer"
test_page "/superadmin/settings" "Settings"
test_page "/superadmin/adoption" "Adoption"
test_page "/superadmin/token-control" "Token Control"

echo "Testing Tenant Main Pages..."
test_page "/tenant" "Tenant Home"
test_page "/tenant/dashboard" "Dashboard"
test_page "/tenant/onboarding" "Onboarding"
test_page "/tenant/trial-expired" "Trial Expired"

echo "Testing Tenant CRM Modules..."
test_page "/tenant/leads" "Leads List"
test_page "/tenant/contacts" "Contacts List"
test_page "/tenant/companies" "Companies List"
test_page "/tenant/deals" "Deals List"
test_page "/tenant/deals/kanban" "Deals Kanban"
test_page "/tenant/tickets" "Tickets List"
test_page "/tenant/tickets/kanban" "Tickets Kanban"

echo "Testing Tenant Sales Pages..."
test_page "/tenant/quotes" "Quotes List"
test_page "/tenant/orders" "Orders List"
test_page "/tenant/invoices" "Invoices List"
test_page "/tenant/contracts" "Contracts List"
test_page "/tenant/offers" "Offers List"
test_page "/tenant/subscriptions" "Subscriptions List"
test_page "/tenant/products" "Products List"
test_page "/tenant/services" "Services"

echo "Testing Tenant Communication..."
test_page "/tenant/calls" "Calls"
test_page "/tenant/sms" "SMS"
test_page "/tenant/chat" "Chat"
test_page "/tenant/email-templates" "Email Templates"
test_page "/tenant/notifications" "Notifications"

echo "Testing Tenant Productivity..."
test_page "/tenant/tasks" "Tasks List"
test_page "/tenant/tasks/kanban" "Tasks Kanban"
test_page "/tenant/calendar" "Calendar"
test_page "/tenant/projects" "Projects List"
test_page "/tenant/approvals" "Approvals"

echo "Testing Tenant Documents..."
test_page "/tenant/documents" "Documents"
test_page "/tenant/docs" "Docs"
test_page "/tenant/kb" "Knowledge Base"
test_page "/tenant/kb/categories" "KB Categories"
test_page "/tenant/esignature" "E-Signature"

echo "Testing Tenant Forms..."
test_page "/tenant/forms" "Forms List"
test_page "/tenant/forms/builder" "Form Builder"

echo "Testing Tenant Analytics..."
test_page "/tenant/analytics" "Analytics"
test_page "/tenant/analytics/forecast" "Forecast"
test_page "/tenant/analytics/email" "Email Analytics"
test_page "/tenant/reports" "Reports"
test_page "/tenant/reports/custom" "Custom Reports"
test_page "/tenant/reports/builder" "Report Builder"
test_page "/tenant/reports/scheduled" "Scheduled Reports"
test_page "/tenant/leaderboards" "Leaderboards"
test_page "/tenant/search" "Search"

echo "Testing Tenant AI Module..."
test_page "/tenant/ai" "AI Home"
test_page "/tenant/ai/lead-scoring" "AI Lead Scoring"
test_page "/tenant/ai/draft" "AI Draft"
test_page "/tenant/ai/activity" "AI Activity"
test_page "/tenant/ai/at-risk" "AI At-Risk"
test_page "/tenant/ai/summarize" "AI Summarize"

echo "Testing Tenant Automation..."
test_page "/tenant/automation" "Automation"
test_page "/tenant/automation/builder" "Automation Builder"
test_page "/tenant/automation/sequences" "Sequences"
test_page "/tenant/sequences" "Sequences Alt"
test_page "/tenant/workflows" "Workflows"

echo "Testing Tenant Integrations..."
test_page "/tenant/integrations" "Integrations"
test_page "/tenant/integrations/connected" "Connected"
test_page "/tenant/integrations/webhooks" "Webhooks"
test_page "/tenant/plugins" "Plugins"

echo "Testing Tenant Settings..."
test_page "/tenant/settings" "Settings Home"
test_page "/tenant/settings/profile" "Profile"
test_page "/tenant/settings/preferences" "Preferences"
test_page "/tenant/settings/team" "Team"
test_page "/tenant/settings/admin" "Admin"
test_page "/tenant/settings/security" "Security"
test_page "/tenant/settings/sessions" "Sessions"
test_page "/tenant/settings/roles" "Roles"
test_page "/tenant/settings/rbac" "RBAC"
test_page "/tenant/settings/hierarchy" "Hierarchy"
test_page "/tenant/settings/territories" "Territories"
test_page "/tenant/settings/pipelines" "Pipelines"
test_page "/tenant/settings/picklists" "Picklists"
test_page "/tenant/settings/custom-fields" "Custom Fields"
test_page "/tenant/settings/assignment-rules" "Assignment Rules"
test_page "/tenant/settings/lead-scoring" "Lead Scoring Rules"
test_page "/tenant/settings/at-risk-rules" "At-Risk Rules"
test_page "/tenant/settings/tags-manager" "Tags Manager"
test_page "/tenant/settings/email" "Email Settings"
test_page "/tenant/settings/notifications" "Notification Settings"
test_page "/tenant/settings/billing" "Billing"
test_page "/tenant/settings/billing/invoices" "Billing Invoices"
test_page "/tenant/settings/bulk-transfer" "Bulk Transfer"
test_page "/tenant/settings/import-export" "Import/Export"
test_page "/tenant/settings/integrations" "Integration Settings"
test_page "/tenant/settings/webhooks" "Webhooks Settings"
test_page "/tenant/settings/webhooks/logs" "Webhook Logs"
test_page "/tenant/settings/api-keys" "API Keys"
test_page "/tenant/settings/sso" "SSO"
test_page "/tenant/settings/login-policy" "Login Policy"
test_page "/tenant/settings/compliance" "Compliance"
test_page "/tenant/settings/audit" "Audit Log"
test_page "/tenant/settings/backup" "Backup"
test_page "/tenant/settings/general" "General Settings"
test_page "/tenant/settings/localization" "Localization"
test_page "/tenant/settings/currency" "Currency"
test_page "/tenant/settings/tax" "Tax Settings"
test_page "/tenant/settings/sla" "SLA"
test_page "/tenant/settings/portal" "Portal Settings"
test_page "/tenant/settings/branding" "Branding"
test_page "/tenant/settings/industry-templates" "Industry Templates"
test_page "/tenant/settings/ai-activity" "AI Activity Settings"
test_page "/tenant/settings/ai-providers" "AI Providers"
test_page "/tenant/settings/ai-templates" "AI Templates"
test_page "/tenant/settings/telegram" "Telegram"
test_page "/tenant/settings/out-of-office" "Out of Office"
test_page "/tenant/settings/user-defaults" "User Defaults"

echo "Testing Tenant Other..."
test_page "/tenant/visitors" "Visitors"
test_page "/tenant/trash" "Trash"
test_page "/tenant/modules" "Modules"
test_page "/tenant/docs" "Documentation"

echo "Testing Dev..."
test_page "/dev/dashboard" "Dev Dashboard"

echo "" >> "$RESULTS_FILE"
echo "========================================" >> "$RESULTS_FILE"
echo "SUMMARY" >> "$RESULTS_FILE"
echo "Total Tested: $((PASS + FAIL))" >> "$RESULTS_FILE"
echo "Passed: $PASS" >> "$RESULTS_FILE"
echo "Failed: $FAIL" >> "$RESULTS_FILE"
echo "========================================" >> "$RESULTS_FILE"

echo "Done! Results in $RESULTS_FILE"
echo "Passed: $PASS, Failed: $FAIL"
