-- dedup: email_warmup_logs (created by 0002_flat_sir_ram)
-- dedup: restore_snapshots (created by 0002_flat_sir_ram)
-- dedup: tenant_backup_records (created by 0002_flat_sir_ram)
-- dedup: tenant_restore_records (created by 0002_flat_sir_ram)
DROP INDEX IF EXISTS "idx_webhook_deliv_payload_g";--> statement-breakpoint
DROP INDEX IF EXISTS "idx_backup_records_created";--> statement-breakpoint
DROP INDEX IF EXISTS "idx_backup_records_expires";--> statement-breakpoint
DROP INDEX IF EXISTS "idx_backup_records_metadata_g";--> statement-breakpoint
DROP INDEX IF EXISTS "idx_whatsapp_templates_unique";--> statement-breakpoint
DROP INDEX IF EXISTS "idx_backup_records_status";--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='lead_assignments') THEN ALTER TABLE "lead_assignments" ALTER COLUMN "lead_id" DROP NOT NULL; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='call_logs') THEN ALTER TABLE "call_logs" ALTER COLUMN "direction" SET DEFAULT 'outbound'; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='email_tracking') THEN ALTER TABLE "email_tracking" ALTER COLUMN "message_id" DROP NOT NULL; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_inbound_logs') THEN ALTER TABLE "webhook_inbound_logs" ALTER COLUMN "payload" DROP NOT NULL; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" ALTER COLUMN "webhook_id" DROP NOT NULL; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" ALTER COLUMN "status" SET DATA TYPE text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" ALTER COLUMN "status" SET DEFAULT 'success'; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" ALTER COLUMN "status" SET NOT NULL; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='backup_records') THEN ALTER TABLE "backup_records" ALTER COLUMN "expires_at" DROP DEFAULT; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='user_departures') THEN ALTER TABLE "user_departures" ALTER COLUMN "user_id" DROP NOT NULL; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='user_departures') THEN ALTER TABLE "user_departures" ALTER COLUMN "departure_date" DROP NOT NULL; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='api_keys') THEN ALTER TABLE "api_keys" ADD COLUMN "call_count" bigint DEFAULT 0; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='api_keys') THEN ALTER TABLE "api_keys" ADD COLUMN "last_used_ip" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='notifications') THEN ALTER TABLE "notifications" ADD COLUMN "body" text NOT NULL; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='notifications') THEN ALTER TABLE "notifications" ADD COLUMN "link" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "locale" text DEFAULT 'en'; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "theme" text DEFAULT 'light'; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "telegram_bot_token" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "telegram_chat_id" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "telegram_enabled" boolean DEFAULT false; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "telegram_notify_login" boolean DEFAULT true; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "telegram_notify_signup" boolean DEFAULT true; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "telegram_notify_password_change" boolean DEFAULT true; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "telegram_notify_2fa_change" boolean DEFAULT true; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='users') THEN ALTER TABLE "users" ADD COLUMN "telegram_notify_security_alerts" boolean DEFAULT true; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='custom_field_defs') THEN ALTER TABLE "custom_field_defs" ADD COLUMN "is_calculated" boolean DEFAULT false; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='custom_field_defs') THEN ALTER TABLE "custom_field_defs" ADD COLUMN "formula" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='deals') THEN ALTER TABLE "deals" ADD COLUMN "company_id" uuid; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='forms') THEN ALTER TABLE "forms" ADD COLUMN "slug" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='forms') THEN ALTER TABLE "forms" ADD COLUMN "title" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='forms') THEN ALTER TABLE "forms" ADD COLUMN "success_message" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='forms') THEN ALTER TABLE "forms" ADD COLUMN "redirect_url" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='forms') THEN ALTER TABLE "forms" ADD COLUMN "submit_label" text DEFAULT 'Submit'; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='forms') THEN ALTER TABLE "forms" ADD COLUMN "theme" jsonb DEFAULT '{}'::jsonb; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='lead_assignments') THEN ALTER TABLE "lead_assignments" ADD COLUMN "contact_id" uuid; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='leads') THEN ALTER TABLE "leads" ADD COLUMN "notes" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='leads') THEN ALTER TABLE "leads" ADD COLUMN "form_id" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='leads') THEN ALTER TABLE "leads" ADD COLUMN "form_submissions_count" integer DEFAULT 0; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='pipelines') THEN ALTER TABLE "pipelines" ADD COLUMN "description" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='pipelines') THEN ALTER TABLE "pipelines" ADD COLUMN "is_default" boolean DEFAULT false; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='call_logs') THEN ALTER TABLE "call_logs" ADD COLUMN "company_id" uuid; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='call_logs') THEN ALTER TABLE "call_logs" ADD COLUMN "duration" integer DEFAULT 0; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='call_logs') THEN ALTER TABLE "call_logs" ADD COLUMN "notes" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='call_logs') THEN ALTER TABLE "call_logs" ADD COLUMN "phone_number" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='call_logs') THEN ALTER TABLE "call_logs" ADD COLUMN "recorded_url" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='call_logs') THEN ALTER TABLE "call_logs" ADD COLUMN "assigned_to" uuid; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='email_tracking') THEN ALTER TABLE "email_tracking" ADD COLUMN "recipient" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='email_tracking') THEN ALTER TABLE "email_tracking" ADD COLUMN "sequence_enrollment_id" uuid; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='email_tracking') THEN ALTER TABLE "email_tracking" ADD COLUMN "open_count" integer DEFAULT 0; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='email_tracking') THEN ALTER TABLE "email_tracking" ADD COLUMN "click_count" integer DEFAULT 0; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_inbound_logs') THEN ALTER TABLE "webhook_inbound_logs" ADD COLUMN "api_key_id" uuid; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_inbound_logs') THEN ALTER TABLE "webhook_inbound_logs" ADD COLUMN "action" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_inbound_logs') THEN ALTER TABLE "webhook_inbound_logs" ADD COLUMN "entity" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_inbound_logs') THEN ALTER TABLE "webhook_inbound_logs" ADD COLUMN "status" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_inbound_logs') THEN ALTER TABLE "webhook_inbound_logs" ADD COLUMN "status_code" integer; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_inbound_logs') THEN ALTER TABLE "webhook_inbound_logs" ADD COLUMN "record_id" uuid; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_inbound_logs') THEN ALTER TABLE "webhook_inbound_logs" ADD COLUMN "payload_size" integer; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='ai_insights') THEN ALTER TABLE "ai_insights" ADD COLUMN "title" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='ai_insights') THEN ALTER TABLE "ai_insights" ADD COLUMN "priority" text DEFAULT 'medium'; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='ai_insights') THEN ALTER TABLE "ai_insights" ADD COLUMN "is_read" boolean DEFAULT false; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" ADD COLUMN "event_type" text DEFAULT 'generic' NOT NULL; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" ADD COLUMN "response_status" integer; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" ADD COLUMN "response_body" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" ADD COLUMN "duration_ms" integer; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='tasks') THEN ALTER TABLE "tasks" ADD COLUMN "completed" boolean DEFAULT false; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='user_departures') THEN ALTER TABLE "user_departures" ADD COLUMN "user_email" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='user_departures') THEN ALTER TABLE "user_departures" ADD COLUMN "user_name" text; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='user_departures') THEN ALTER TABLE "user_departures" ADD COLUMN "departed_by" uuid; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='user_departures') THEN ALTER TABLE "user_departures" ADD COLUMN "contacts_reassigned_to" uuid; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='user_departures') THEN ALTER TABLE "user_departures" ADD COLUMN "contacts_count" integer DEFAULT 0; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='user_departures') THEN ALTER TABLE "user_departures" ADD COLUMN "deals_count" integer DEFAULT 0; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='user_departures') THEN ALTER TABLE "user_departures" ADD COLUMN "tasks_count" integer DEFAULT 0; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='email_warmup_logs') THEN CREATE INDEX "idx_email_warmup_logs_config" ON "email_warmup_logs" USING btree ("config_id","created_at"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='restore_snapshots') THEN CREATE INDEX "idx_restore_snapshots_tenant" ON "restore_snapshots" USING btree ("tenant_id"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='tenant_backup_records') THEN CREATE INDEX "idx_tenant_backup_tenant" ON "tenant_backup_records" USING btree ("tenant_id","status"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='tenant_backup_records') THEN CREATE INDEX "idx_tenant_backup_status" ON "tenant_backup_records" USING btree ("status","created_at"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='tenant_backup_records') THEN CREATE INDEX "idx_tenant_backup_expires" ON "tenant_backup_records" USING btree ("expires_at") WHERE status = 'completed'; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='tenant_restore_records') THEN CREATE INDEX "idx_tenant_restore_tenant" ON "tenant_restore_records" USING btree ("tenant_id","status"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='tenant_restore_records') THEN CREATE INDEX "idx_tenant_restore_backup" ON "tenant_restore_records" USING btree ("backup_id"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='forms') THEN CREATE UNIQUE INDEX "idx_forms_slug" ON "forms" USING btree ("slug"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='lead_assignments') THEN CREATE INDEX "idx_lead_assignments_contact" ON "lead_assignments" USING btree ("contact_id"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='email_warmup_configs') THEN CREATE UNIQUE INDEX "idx_email_warmup_unique" ON "email_warmup_configs" USING btree ("tenant_id","from_email"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_inbound_logs') THEN CREATE INDEX "idx_webhook_inbound_logs_api_key" ON "webhook_inbound_logs" USING btree ("api_key_id"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='automation_workflows') THEN CREATE UNIQUE INDEX "idx_automation_workflows_tenant_workflow" ON "automation_workflows" USING btree ("tenant_id","workflow_id"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN CREATE INDEX "idx_webhook_deliv_webhook" ON "webhook_deliveries" USING btree ("webhook_id"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN CREATE INDEX "idx_webhook_deliv_status" ON "webhook_deliveries" USING btree ("status"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN CREATE INDEX "idx_webhook_deliveries_metadata_g" ON "webhook_deliveries" USING gin ("metadata"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='onboarding_progress') THEN CREATE UNIQUE INDEX "idx_onboarding_progress_unique" ON "onboarding_progress" USING btree ("tenant_id","user_id","step_name"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='platform_settings') THEN CREATE UNIQUE INDEX "idx_platform_settings_global_unique" ON "platform_settings" USING btree ("key") WHERE "platform_settings"."tenant_id" is null; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='platform_settings') THEN CREATE UNIQUE INDEX "idx_platform_settings_tenant_unique" ON "platform_settings" USING btree ("key","tenant_id") WHERE "platform_settings"."tenant_id" is not null; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='whatsapp_templates') THEN CREATE UNIQUE INDEX "idx_whatsapp_templates_unique" ON "whatsapp_templates" USING btree ("tenant_id","name","language"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='backup_records') THEN CREATE INDEX "idx_backup_records_status" ON "backup_records" USING btree ("status","completed_at"); END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='notifications') THEN ALTER TABLE "notifications" DROP COLUMN "message"; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='call_logs') THEN ALTER TABLE "call_logs" DROP COLUMN "duration_seconds"; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='call_logs') THEN ALTER TABLE "call_logs" DROP COLUMN "summary"; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" DROP COLUMN "response"; END IF; END $$;--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='webhook_deliveries') THEN ALTER TABLE "webhook_deliveries" DROP COLUMN "error"; END IF; END $$;--> statement-breakpoint
