var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/csrf-token/route.js")
R.c("server/chunks/node_modules_drizzle-orm_1227x6w._.js")
R.c("server/chunks/[root-of-the-server]__0vyops4._.js")
R.c("server/chunks/[root-of-the-server]__0w~.nyl._.js")
R.c("server/chunks/[root-of-the-server]__0e6esfj._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_01jwzjp._.js")
R.c("server/chunks/[root-of-the-server]__016fwb8._.js")
R.c("server/chunks/drizzle_schema_08h5x64._.js")
R.c("server/chunks/_0p_71eh._.js")
R.c("server/chunks/[root-of-the-server]__00bl0kj._.js")
R.c("server/chunks/node_modules_drizzle-orm_0hgsuc1._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/_0-~8_z7._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_csrf-token_route_actions_02oh57u.js")
R.m(655963)
module.exports=R.m(655963).exports
