var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/p/offers/[publicToken]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00rk9o0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_10q.2r1.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rhnz_j._.js")
R.c("server/chunks/ssr/node_modules_0de7ei2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__10m7bq5._.js")
R.c("server/chunks/ssr/app_error_tsx_11t4ysq._.js")
R.c("server/chunks/ssr/app_not-found_tsx_0u42gv_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/app_global-error_tsx_0m9qisk._.js")
R.c("server/chunks/ssr/_next-internal_server_app_p_offers_[publicToken]_page_actions_0vj60.1.js")
R.m(507112)
module.exports=R.m(507112).exports
