var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/verify-email/route.js")
R.c("server/chunks/node_modules_drizzle-orm_1227x6w._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_01jwzjp._.js")
R.c("server/chunks/[root-of-the-server]__0vyops4._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/_0-~8_z7._.js")
R.c("server/chunks/[root-of-the-server]__106gilt._.js")
R.c("server/chunks/node_modules_072rfkg._.js")
R.c("server/chunks/node_modules_zod_v4_classic_0zwdsy2._.js")
R.c("server/chunks/[root-of-the-server]__0e6esfj._.js")
R.c("server/chunks/_0p_71eh._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/drizzle_schema_08h5x64._.js")
R.c("server/chunks/node_modules_drizzle-orm_0hgsuc1._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_verify-email_route_actions_0y0eghp.js")
R.m(703961)
module.exports=R.m(703961).exports
