var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/flags/route.js")
R.c("server/chunks/_11pdgth._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_01jwzjp._.js")
R.c("server/chunks/[root-of-the-server]__00bl0kj._.js")
R.c("server/chunks/[root-of-the-server]__0e6esfj._.js")
R.c("server/chunks/node_modules_next_dist_0npcise._.js")
R.c("server/chunks/[root-of-the-server]__0rk6b06._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_flags_route_actions_0e0ei31.js")
R.m(798227)
module.exports=R.m(798227).exports
